name: scan

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    uses: bl4ko/shared-actions/.github/workflows/gitleaks.yml@c0f9713f3072bc2e58f794d49e14ffe4a3ceba31 # main
