name: scan

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    uses: bl4ko/shared-actions/.github/workflows/gitleaks.yml@baf01ff7a2e378a733283b1a26dd56d8108cf4e2 # main
